apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  admin.enabled: "true"
  accounts.admin: "login,apiKey"
  server.insecure: "true"
  url: "https://localhost:8080"
