global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'k8s-demo-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - 'alert-rules.yml'

scrape_configs:
  # Prometheus server metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Application metrics
  - job_name: 'k8s-demo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker container metrics (if using docker-compose)
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']

  # Node exporter (if available)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  # Kubernetes metrics (if running in Kubernetes)
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
/nbbuild/
/dist/
/nbdist/
/.nb-gradle/

# macOS
.DS_Store
.AppleDouble
.LSOverride
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
.classpath
.project

# Linux
*~

# Temporary files
*.tmp
*.bak
*.swp
*~

# OS specific
thumbs.db
.DS_Store
desktop.ini

# Docker
.dockerignore
docker-compose.override.yml

# Kubernetes
.kubeconfig
kubeconfig

# ArgoCD
argocd-server
argocd-cli

# Node modules (if using any Node tools)
node_modules/
npm-debug.log
yarn-error.log

# Python
__pycache__/
*.py[cod]
*$py.class
.Python
env/
venv/
ENV/

# Environment variables
.env
.env.local
.env.*.local

# Secrets
*.pem
*.key
secrets/
.secrets
*.encrypted

# Build outputs
dist/
build/
*.class
*.jar
*.war

# IDE
.idea/
.vscode/
*.swp
*.swo
*~
.DS_Store

# Maven
target/
.m2/

# Gradle
.gradle/
build/

# SonarQube
.sonar/
.sonarqube/

# Checkstyle
checkstyle-result.xml

# JaCoCo
*.exec
.jacoco/

# Code coverage
coverage/
.coverage
htmlcov/

# Test reports
TEST-*.xml
surefire-reports/
failsafe-reports/

# Dependency Check
dependency-check-report.*

# Git
.git/
.gitkeep

# CI/CD
.github/workflows/logs/

# Spring Boot
application-local.properties
application-dev.properties
application-test.properties

# Database files
*.db
*.sqlite
*.h2.db

# Temp directories
temp/
tmp/
*.tmp

# Backups
*.backup
*.bak

# Certificates
*.crt
*.cert
*.der
*.pem
*.key
*.jks
*.keystore

# Lock files (optional - uncomment if needed)
# package-lock.json
# yarn.lock

# OS generated files
.vscode/
.idea/
*.iml

# Build artifacts
*/target/
*/build/

# Local development
.local/
local/

# Helm
charts/
Chart.lock

# Kustomize
kustomization.yaml.bak

# Miscellaneous
*.orig
*.rej
HELP.md
.gradle
gradlew
gradlew.bat
gradle/
# Compiled class file
*.class

# Log file
*.log
logs/
*.log.*

# Package Files #
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# Maven
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties
dependency-reduced-pom.xml
.flattened-pom.xml
.m2/

# Eclipse
.classpath
.project
.settings/
*.launch
.buildpath
.sts4-cache/
.factorypath

# IntelliJ IDEA
.idea/
*.iml
*.iws
*.ipr
out/

# VS Code
.vscode/
*.code-workspace
.devcontainer/

# Gradle
.gradle/
build/
!gradle-wrapper.jar
!gradle/wrapper/gradle-wrapper.jar

# NetBeans
/nbproject/private/

