apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-demo-config
  namespace: k8s-demo
  labels:
    app: k8s-demo
data:
  application.properties: |
    server.shutdown=graceful
    server.servlet.context-path=/
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.show-details=when-authorized
    management.health.livenessState.enabled=true
    management.health.readinessState.enabled=true
    logging.level.root=INFO
    logging.level.com.example.k8s=DEBUG
    spring.application.name=k8s-demo
    spring.profiles.active=production
  logback-spring.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
      <springProfile name="production">
        <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
          <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
          </encoder>
        </appender>
        <root level="INFO">
          <appender-ref ref="CONSOLE"/>
        </root>
      </springProfile>
    </configuration>

