apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-demo-config
  labels:
    app: k8s-demo
data:
  application.properties: |
    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
    management.health.livenessState.enabled=true
    management.health.readinessState.enabled=true

