apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-simple-app
  namespace: my-simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-simple-app
  template:
    metadata:
      labels:
        app: my-simple-app
    spec:
      containers:
        - name: my-simple-app
          image: tamdz1201/my-simple-app:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
