apiVersion: v1
kind: Namespace
metadata:
  name: k8s-demo
  labels:
    name: k8s-demo
    app.kubernetes.io/name: k8s-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-demo
  namespace: k8s-demo
  labels:
    app: k8s-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-demo
  namespace: k8s-demo
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-demo
  namespace: k8s-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-demo
subjects:
- kind: ServiceAccount
  name: k8s-demo
  namespace: k8s-demo

