apiVersion: v1
kind: Service
metadata:
  name: my-simple-app-service
  namespace: my-simple-app
spec:
  selector:
    app: my-simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
