apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-service
  labels:
    app: k8s-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: k8s-demo

