apiVersion: v1
kind: Service
metadata:
  name: my-simple-app
  namespace: my-simple-app
spec:
  type: ClusterIP
  selector:
    app: my-simple-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
