name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: tamdz1201/my-simple-app:latest

      - name: Update deployment manifest
        if: github.ref == 'refs/heads/main'
        run: |
          sed -i "s|image: .*|image: tamdz1201/my-simple-app:latest|g" k8s/deployment.yaml
          echo "Updated deployment.yaml:"
          cat k8s/deployment.yaml

      - name: Commit and push manifest changes
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add k8s/deployment.yaml
          git commit -m "chore: update image tag to latest" || true
          git push || echo "No changes to push"
